size:
  width: 10
  height: 10
  scale: 0.5

zones:
#以下を変更する場合，
#zone.pyxのthe_generate_ag_zoneとspecified_range_generate_ac_zoneも変える
#（ハードコーディングのため）
  - name: zone1
    pose: [7.5,2.5]
    shape: [1,0]
    width: 1.0
  - name: zone2
    pose: [1.5,2.5]
    shape: [1,0]
    width: 1
  - name: zone3
    pose: [7.5,5.0]
    shape: [1,0]
    width: 1
  - name: zone4
    pose: [1.5,5.0]
    shape: [1,0]
    width: 1
  - name: zone5
    pose: [7.5,7.5]
    shape: [1,0]
    width: 1
  - name: zone6
    pose: [1.5,7.5]
    shape: [1,0]
    width: 1
  - name: zone7
    pose: [4.5,1.0]
    shape: [1,0]
    width: 1
  - name: zone8
    pose: [4.5,9.0]
    shape: [1,0]
    width: 1

viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 10
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1

#walls:
#  - name: wall1
#    pose: [0.0,0.0]
#    shape: [0,10]
#    width: 1
#  - name: wall2
#    pose: [0.0,0.0]
#    shape: [10,0]
#    width: 1
#  - name: wall3
#    pose: [0.0,10]
#    shape: [10,0]
#    width: 1 
#    shape: [0,10]
#    width: 1
#  - name: wall5
#    pose: [2.5,4.5]
#    shape: [0,2]
#    width: 0.5
#  - name: wall6
#    pose: [4.0,7.0]
#    shape: [2,0]
#    width: 0.5
#  - name: wall7 
#    pose: [7.5,4.5]
#    shape: [0,2]
#    width: 0.5
#  - name: wall8
#    pose: [4.0,4.0]
#    shape: [2.0,0]
#   width: 0.5

#nodes:
#  - name: node1
#    pose: [2,3.0]
#  - name: node2
#    pose: [3,3]
#  - name: node3
#    pose: [7,3]
#  - name: node4
#    pose: [3,7]
#  - name: node5
#    pose: [7,7]

